version: '3.12.9'

services:
  django:
    image: django-docker:0.0.1
    build: .
    ports:
      - 8080:8080
    environment:
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST} 
      DATABASE_PORT: ${DATABASE_PORT}
    depends_on:
      - db

  db:
    image: postgres:latest
    platform: linux/arm64
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    expose:
      - 5432

volumes:
  db-data:
