# Generated by Django 5.1.5 on 2025-02-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_managers_remove_user_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='department_image',
            field=models.ImageField(default='', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='doctor',
            name='doctor_image',
            field=models.ImageField(default='', null=True, upload_to=''),
        ),
    ]
